server:
  port: 8088
  servlet:
    context-path: /phonestore
#logging:
#  level:
#    org.springframework: debug
spring:
  freemarker:
    charset: UTF-8
  ## 配置数据源信息
  datasource:
    username: scott
    password: orcl
    url: jdbc:oracle:thin:@localhost:1521:phone
    driver-class-name: oracle.jdbc.OracleDriver
  mail:
    #QQ邮箱这不用改
    host: smtp.qq.com
#    #你的邮箱
#    username: 2098382492@qq.com
#    #你的授权码
#    password: uheqqheoenitdjdj
    default-encoding: UTF-8
  redis:
    #redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 0
        #连接超时时间（毫秒）
    timeout: 30000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
## 配置mapper映射文件路径
  mapper-locations: classpath:mapper/*.xml
## 配置扫描实体包，给实体类设置别名
  type-aliases-package: com.msy.phonestore.pojo

logging:
  level:
    com.lawt.repository.mapper: debug

