server:
  port: 8088
  servlet:
    context-path: /phonestore
#logging:
#  level:
#    org.springframework: debug
spring:
  freemarker:
    charset: UTF-8
    ## 配置数据源信息
  datasource:
    username: scott
    password: orcl
    url: jdbc:oracle:thin:@localhost:1521:phone
    driver-class-name: oracle.jdbc.OracleDriver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
## 配置mapper映射文件路径
  mapper-locations: classpath:mapper/*.xml
## 配置扫描实体包，给实体类设置别名
  type-aliases-package: com.msy.phonestore.pojo

logging:
  level:
    com.lawt.repository.mapper: debug

